

file.dir: /home/lhs/csv/
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/csv-to-db
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true

logging.level:
  root: info
  com.hansoleee.csvtodb: debug